### ISSUE TITLE
tradeoffs with package vs docker

### ISSUE THREAD

**Issue by will** [nirev/synology-tailscale#10]
Lately I've been installing most random stuff on my synology with docker-compose vs going through packages. I found this first though when looking around for how to run tailscale on my nas.

I wonder though if there are any advantages or disadvantages for doing it this way as a package or through docker. Maybe it doesn't matter much either way?

**Comment by nirev** [comment]
Hey, @will! I don't think there's much difference to be honest.

I haven't tried it, but I imagine it should work if you create the container using host network.
I guess you'd still need to create /dev/net/tun and mount it as necessary.
Similar to what is described here: https://haugene.github.io/docker-transmission-openvpn/synology-nas/
You'd also need to mount a volume to keep tailscale state file outside of the container, so you don't lose keys when updating versions.

The different from this is that at some point in the future I do want to set up a synology package repository, so you'd get automatic updates using Synology DSM. But other than that, if you know what you're doing, then I don't really see that much difference.

**Comment by will** [comment]
I gave it some thought, and decided it'd be a lot easier to just use your package and so my laziness won out. 

Seems to be working, was able to connect from my phone while on cellular. Thank you!

DS1019+ on DSM 6.2.2
