### ISSUE TITLE
compile netfilter modules for every platform

### ISSUE THREAD

**Issue by nirev** [nirev/synology-tailscale#17]
Synology DSM is missing some netfilter modules that are necessary for tailscale to properly work
https://github.com/tailscale/tailscale/issues/451

One thing that could be done is compile those modules for every platform.

references:
- https://github.com/marcomezzaro/synok3s
- https://github.com/SynologyOpenSource/HelloKernel

**Comment by demoulin** [comment]
@nirev do you have this working for your machine/kernel?

**Comment by nirev** [comment]
@demoulin not yet. this is something I was thinking about but haven't had the time to do yet

**Comment by bradfitz** [comment]
I think we can skip this bug and use https://github.com/tailscale/tailscale/issues/707 instead.

I have a few Synology units at home. I'll try to get Tailscale working out of the box on them, automatically using the userspace subnet relay code instead.  (Upstream bug: https://github.com/tailscale/tailscale/issues/582)

**Comment by jucor** [comment]
Very exciting, thanks @bradfitz and @nirev !

**Comment by nirev** [comment]
Thank you, @bradfitz!! This is amazing news! 
Going to close this one.

❤️ 💛 💙 🖤 💜 💚
