### ISSUE TITLE
v0.98-0 a valid release ?

### ISSUE THREAD

**Issue by rixrix** [nirev/synology-tailscale#18]
Hi, 
thanks for your work on this. 

apology if I missed something but the release "v0.98-0" doesn't contain anything special, other than gitignore and readme changes ? thanks

**Comment by nirev** [comment]
@rixrix Hi, I should make this more explicit, but the main change was updating the tailscale binary to 0.98
this is the official changelog: https://github.com/tailscale/tailscale/releases/tag/v0.98
