### ISSUE TITLE
DiskStation DS3617xs  - Intel® Xeon® Processor D-1527 (Broadwell)

### ISSUE THREAD

**Issue by dazzag24** [nirev/synology-tailscale#37]
Hi,

Any ideas if this would run on a DiskStation DS3617xs  which has this CPU: Intel® Xeon® Processor D-1527 (Broadwell)?

Thanks

**Comment by nirev** [comment]
It should run fine with the `amd64` version
(https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures)
