### ISSUE TITLE
DS418play: having trouble running `tailscale up`

### ISSUE THREAD

**Issue by mhansen** [nirev/synology-tailscale#7]
Hi there, this is a cool project! Thought I'd report the trouble I was having in case others are too or it's helpful. Thanks for setting this up.

I've got a DS418play, which is x86_64:
```
$ uname -a
Linux monastery 4.4.59+ #25423 SMP PREEMPT Tue Apr 14 14:29:10 CST 2020 x86_64 GNU/Linux synology_apollolake_418play
```
I tried installing https://github.com/nirev/synology-tailscale/releases/tag/v0.97-45_spkbuild2 through the UI. `ps` tells me that tailscaled is up:

```
admin@monastery:/var/packages/tailscale/target/bin$ ps aux | grep tailsca
root     19209  0.2  2.7 472628 51156 ?        Sl   21:28   0:02 /volume1/@appstore/tailscale/bin/tailscaled --state=/volume1/@appstore/tailscale/var/tailscaled.state --socket=/volume1/@appstore/tailscale/var/tailscaled.sock --port=41641
```

But I can't run `sudo tailscale up` on the NAS logged in as `admin`: probably a PATH issue

```
$ sudo tailscale up
sudo: tailscale: command not found
```

Not to be deterred, I try finding tailscale and running it directly from the folder it's installed in, and I get a bit further:

```
sudo /var/packages/tailscale/target/bin/tailscale up
logtail started
Program starting: v0.97-45-g02c73501: []string{"/var/packages/tailscale/target/bin/tailscale", "up"}
LogID: 843a054623be22b70f9365dc5749ff59b62d276283f7c7b47ab8123b26f75dc1
Failed to connect to connect to tailscaled. (safesocket.Connect: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory)
```

I wonder what socket tailscaled is using if not `/var/run/tailscale/tailscaled.sock`... looks like `/var/packages/tailscale/target/var/tailscale.sock`.

**Comment by nirev** [comment]
Hey, @mhansen!
Thanks for trying this and reporting back.
let's fix this!

1) What's the DSM version you're running?
2) there should be an install log in `/tmp/tailscale_install.log`. can you post it here?
3) the install script should put a wrapper for tailscale in `/usr/local/bin/tailscale`
can you check if it's there?

that all being said..
you can run tailscale with:
```
sudo /var/packages/tailscale/target/bin/tailscale up --socket=/var/packages/tailscale/target/var/tailscale.sock
```

**Comment by mhansen** [comment]
DSM Version: `DSM 6.2.3-25423`

Here's the logs, they include installing and uninstalling:

```
admin@monastery:~$ cat /tmp/tailscale_install.log

>> 2020-05-13T21:28:28+1000 :: postinst
mkdir: created directory '/var/packages/tailscale/target/var'
chmod: cannot access '/usr/local/bin/tailscale': No such file or directory
failed to change mode of '/usr/local/bin/tailscale' from 0000 (---------) to 0000 (---------)
'/usr/local/etc/logrotate.d/tailscaled' -> '/var/packages/tailscale/target/conf/logrotate.conf'

>> 2020-05-13T21:48:21+1000 :: pospostuninsttinst
rm: cannot remove '/usr/local/bin/tailscale': No such file or directory
removed '/usr/local/etc/logrotate.d/tailscaled'
```

**Comment by mhansen** [comment]
`/usr/local/bin/tailscale` doesn't exist:

```
admin@monastery:~$ /usr/local/bin/tailscale
-sh: /usr/local/bin/tailscale: No such file or directory
```

**Comment by mhansen** [comment]
Looking at `installer`, there's a step that does `echo "#!/bin/bash" >/usr/local/bin/tailscale`.

Maybe `set -e` on the bash script to tell it to exit on any error might help? I'm guessing that silently failed due to some permission errors writing to `/usr/local/bin/tailscale`.

**Comment by mhansen** [comment]
Ah, the problem: I have no `/usr/local/bin`:

```
admin@monastery:/usr/local$ cd /usr/local
admin@monastery:/usr/local$ ls
etc  lib  libexec  packages  share
admin@monastery:/usr/local$ cd bin
-sh: cd: bin: No such file or directory
```

**Comment by mhansen** [comment]
Although weirdly despite having no `/usr/local/bin` directory, it's in my `$PATH`!

```
admin@monastery:/usr/local$ echo $PATH
/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin
```

**Comment by nirev** [comment]
oh wow!
that's very interesting. I assumed it would always be there, as it's the recommended place to install binaries from Synology packages, according to the dev docs!

`set -e` may be a good idea indeed.
I'll see how Synology handles it when the install script fails.

I'll also check other official packages to see how they handle it. Perhaps I should create `/usr/local/bin` if it doesn't exist yet.

**Comment by mhansen** [comment]
Here's a similar issue: https://github.com/duplicati/duplicati/issues/1854

**Comment by nirev** [comment]
> This is kind of wild, I don't think I've ever seen a linux system without a /usr/local/bin before.

Synology DSM is crazy!

**Comment by mhansen** [comment]
This person also had to `mkdir /usr/local/bin`: 
https://chainsawonatireswing.com/2012/01/08/set-up-the-synology-diskstation-ds411j-to-support-utf-8/

**Comment by mhansen** [comment]
Finally one more example of someone `mkdir /usr/bin/local`: 
https://community.spiceworks.com/topic/1287119-backing-up-a-synology?page=1#entry-5227399

I might file a bug with Synology about this - surely it's a bug to omit the directory since it's present in `$PATH`.

**Comment by nirev** [comment]
Also, this: https://github.com/SynoCommunity/spksrc/search?q=%22mkdir+-p+%2Fusr%2Flocal%2Fbin%22&unscoped_q=%22mkdir+-p+%2Fusr%2Flocal%2Fbin%22

**Comment by mhansen** [comment]
Wow this is bananas, how many people have been hit by this issue. I'll open a support ticket with Synology.

**Comment by nirev** [comment]
Great find! Thank you for reporting!
It's likely that those who installed it had previously installed another package that created `/usr/local/bin`. In my case it may have been the Docker package.

I'm going to do the same regardless, as I don't want the issue happening again. 
But wow.

**Comment by mhansen** [comment]
I've filed support ticket number 2529601 with Synology.

**Comment by nirev** [comment]
Thank you!
In the meantime, can you try https://github.com/nirev/synology-tailscale/releases/tag/v0.97-45_spkbuild3 ?

**Comment by mhansen** [comment]
That new build works perfectly for me, thank you! This has been fun
debugging this with you, thanks again for putting this out there for people
to use :-)

**Comment by mhansen** [comment]
Fixed in https://github.com/nirev/synology-tailscale/commit/7798a14af50dfc2285c642180a31b8d854403f09

**Comment by mhansen** [comment]
FYI I heard back from Synology, attaching their comment for posterity:

> Dear Customer,
> 
>  
> 
> Thank you for contacting Synology support.
> 
>  
> 
> Thank you for your information.
> 
> Since the path only include our package binary.
> 
> Our code will create when we need this folder.
> 
> I apologize for your inconvenience.
> 
> However, I have passed this message to our developers and product management group.
> 
> They will have more research on such feature. Thank you for bringing this issue to our attention.
> 
> For now, please use mkdir as workaround.
> 
>  
> 
> If there is any problem, please feel free to contact us.

**Comment by nirev** [comment]
Amazing. Thank you for sharing :)

This really was fun debugging!
